apiVersion: v1
kind: Service
metadata:
  name: content-moderator-fe
  namespace: luis
spec:
  type: NodePort   
  ports:
  - port: 30001      
    targetPort: 5173 
    nodePort: 30001  
  selector:
    app: content-moderator-fe